---
# start_and_or_enable_systemd_service/tasks/main.yml

- name: "Start the {{ service_name }} service"
  service:
    name: "{{ service_name }}"
    state: 'started'
  when: 'service_started | bool'

- name: "Enable the {{ service_name }} service"
  service:
    name: "{{ service_name }}"
    enabled: 'true'
  when: 'service_enabled | bool'
