---
# start_and_or_enable_systemd_service/tasks/main.yml

- name: "Start the service {{ service_name }}"
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: 'started'
  when:
    - 'service_started is defined'
    - 'service_started | bool'

- name: "Enable the service {{ service_name }}"
  ansible.builtin.service:
    name: "{{ service_name }}"
    enabled: 'true'
  when:
    - 'service_enabled is defined'
    - 'service_enabled | bool'

- name: "Stop the service {{ service_name }}"
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: 'stopped'
  when:
    - 'service_started is defined'
    - 'not service_started | bool'

- name: "Disable the service {{ service_name }}"
  ansible.builtin.service:
    name: "{{ service_name }}"
    enabled: 'false'
  when:
    - 'service_enabled is defined'
    - 'not service_enabled | bool'

- name: "Restart the service {{ service_name }}"
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: 'restarted'
  when:
    - 'service_restarted is defined'
    - 'service_restarted | bool'
